Namespace PerformFlow in BaseJob#restart_flow to prevent loading issue
Prevents:

```
ArgumentError: A copy of Cangaroo::BaseJob has
been removed from the module tree but is still active!
```

The issue this prevents can be reproduced with a fresh Rails 4.2.10 app
using the bleeding-edge Cangaroo gem. See this project for an example:

https://github.com/davidlaprade/cangaroo-loading-issue#to-reproduce